In [1]:
import pandas as pd
df = pd.read_csv('sales_dataset.csv')
df.head()

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Column1
0,0,2/19/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.0,NaN
1,1,2/20/2016,2016.0,February,29.0,F,United States,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.0,NaN
2,2,2/27/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.0,NaN
3,3,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.0,NaN
4,4,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.0,NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34867 entries, 0 to 34866
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             34867 non-null  int64
 1   Date              34866 non-null  object
 2   Year              34866 non-null  float64
 3   Month             34866 non-null  object
 4   Customer Age      34866 non-null  float64
 5   Customer Gender   34866 non-null  object
 6   Country           34866 non-null  object
 7   State             34866 non-null  object
 8   Product Category  34866 non-null  object
 9   Sub Category      34866 non-null  object
 10  Quantity          34866 non-null  float64
 11  Unit Cost         34866 non-null  float64
 12  Unit Price        34866 non-null  float64
 13  Cost              34866 non-null  float64
 14  Revenue           34867 non-null  float64
 15  Column1           2574 non-null   float64
dtypes: float64(8), int64(1), object(7)
memory usage: 4.3+ MB

In [3]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
34862    False
34863    False
34864    False
34865    False
34866    False
Length: 34867, dtype: bool

In [8]:
df.drop_duplicates()

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Column1
0,0,2/19/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.000000,NaN
1,1,2/20/2016,2016.0,February,29.0,F,United States,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.000000,NaN
2,2,2/27/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.000000,NaN
3,3,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.000000,NaN
4,4,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34862,34862,2/7/2016,2016.0,February,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,2.0,1160.00,985.500000,2320.0,1971.000000,NaN
34863,34863,3/13/2015,2015.0,March,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2049.00,1583.000000,2049.0,1583.000000,NaN
34864,34864,4/5/2015,2015.0,April,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,3.0,683.00,560.666667,2049.0,1682.000000,NaN
34865,34865,8/30/2015,2015.0,August,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2320.00,1568.000000,2320.0,1568.000000,NaN
34866,34866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,641.532095,NaN

In [9]:
df['Revenue'].unique()

array([ 109.      ,   57.      ,   15.      , ..., 1748.      ,
       1971.      ,  641.532095])

In [10]:
df.drop(columns=['Column1'])

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue
0,0,2/19/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.000000
1,1,2/20/2016,2016.0,February,29.0,F,United States,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.000000
2,2,2/27/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.000000
3,3,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.000000
4,4,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34862,34862,2/7/2016,2016.0,February,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,2.0,1160.00,985.500000,2320.0,1971.000000
34863,34863,3/13/2015,2015.0,March,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2049.00,1583.000000,2049.0,1583.000000
34864,34864,4/5/2015,2015.0,April,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,3.0,683.00,560.666667,2049.0,1682.000000
34865,34865,8/30/2015,2015.0,August,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2320.00,1568.000000,2320.0,1568.000000
34866,34866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,641.532095

In [11]:
df.rename(columns={'Unit Price': 'Unit Per Price'}, inplace=True)

In [12]:
 df.reindex()

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Per Price,Cost,Revenue,Column1
0,0,2/19/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.000000,NaN
1,1,2/20/2016,2016.0,February,29.0,F,United States,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.000000,NaN
2,2,2/27/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.000000,NaN
3,3,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.000000,NaN
4,4,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34862,34862,2/7/2016,2016.0,February,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,2.0,1160.00,985.500000,2320.0,1971.000000,NaN
34863,34863,3/13/2015,2015.0,March,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2049.00,1583.000000,2049.0,1583.000000,NaN
34864,34864,4/5/2015,2015.0,April,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,3.0,683.00,560.666667,2049.0,1682.000000,NaN
34865,34865,8/30/2015,2015.0,August,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2320.00,1568.000000,2320.0,1568.000000,NaN
34866,34866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,641.532095,NaN

In [13]:
df.isna().sum()

index                   0
Date                    1
Year                    1
Month                   1
Customer Age            1
Customer Gender         1
Country                 1
State                   1
Product Category        1
Sub Category            1
Quantity                1
Unit Cost               1
Unit Per Price          1
Cost                    1
Revenue                 0
Column1             32293
dtype: int64

In [14]:
df.dropna()

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Per Price,Cost,Revenue,Column1
312,312,1/11/2016,2016.0,January,40.0,M,France,Yveline,Bikes,Road Bikes,3.0,567.00,790.0,1701.0,2370.0,2370.000000
313,313,1/11/2016,2016.0,January,40.0,M,France,Yveline,Accessories,Helmets,2.0,192.50,199.0,385.0,398.0,398.000000
314,314,1/18/2016,2016.0,January,40.0,M,France,Yveline,Bikes,Mountain Bikes,2.0,1160.00,1511.5,2320.0,3023.0,3023.000000
315,315,1/18/2016,2016.0,January,40.0,M,France,Yveline,Accessories,Bottles and Cages,2.0,115.00,147.0,230.0,294.0,294.000000
316,316,1/18/2016,2016.0,January,40.0,M,France,Yveline,Accessories,Bottles and Cages,1.0,140.00,167.0,140.0,167.0,167.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2881,2881,1/5/2016,2016.0,January,28.0,M,United Kingdom,England,Accessories,Fenders,2.0,176.00,229.0,352.0,458.0,1971.000000
2882,2882,1/7/2016,2016.0,January,28.0,M,United Kingdom,England,Accessories,Fenders,1.0,506.00,590.0,506.0,590.0,1583.000000
2883,2883,2/20/2016,2016.0,February,28.0,M,United Kingdom,England,Accessories,Fenders,3.0,117.33,159.0,352.0,477.0,1682.000000
2884,2884,2/24/2016,2016.0,February,28.0,M,United Kingdom,England,Accessories,Fenders,1.0,286.00,390.0,286.0,390.0,1568.000000
2935,2935,2/19/2016,2016.0,February,52.0,M,France,Hauts de Seine,Clothing,Jerseys,1.0,1250.00,1644.0,1250.0,1644.0,687.344828

In [17]:
df.fillna(0, inplace=True)

In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='constant', fill_value=0)

In [55]:
df = pd.read_csv('sales_dataset.csv')

In [56]:
df.columns

Index(['index', 'Date', 'Year', 'Month', 'Customer Age', 'Customer Gender',
       'Country', 'State', 'Product Category', 'Sub Category', 'Quantity',
       'Unit Cost', 'Unit Price', 'Cost', 'Revenue', 'Column1'],
      dtype='object')

In [57]:
num_cols = df.select_dtypes(include=['number']).columns
df[num_cols] = imputer.fit_transform(df[num_cols])

In [58]:
df['Date'] = pd.to_datetime(df['Date'])

In [59]:
df['Cost'] = pd.to_numeric(df['Cost'])

In [60]:
df['Customer Age'] = pd.to_numeric(df['Customer Age'], errors='coerce')

In [61]:
df['Customer Age'] = df['Customer Age'].astype('Int64')

In [62]:
df['Country'] = df['Country'].str.replace('USA', 'United States')

In [63]:
df['Country'] = df['Country'].str.lower()

In [64]:
df.head()

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Column1
0,0.0,2016-02-19,2016.0,February,29,F,united states,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.0,0.0
1,1.0,2016-02-20,2016.0,February,29,F,united states,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.0,0.0
2,2.0,2016-02-27,2016.0,February,29,F,united states,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.0,0.0
3,3.0,2016-03-12,2016.0,March,29,F,united states,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.0,0.0
4,4.0,2016-03-12,2016.0,March,29,F,united states,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.0,0.0

In [65]:
df['Country'].str.strip()

0        united states
1        united states
2        united states
3        united states
4        united states
             ...
34862           france
34863           france
34864           france
34865           france
34866              NaN
Name: Country, Length: 34867, dtype: object

In [67]:
np.where(df['Revenue'] > 1000, 'High', 'Low')

array(['Low', 'Low', 'Low', ..., 'High', 'High', 'Low'], dtype='<U4')

In [68]:
df['Country'].replace('usa', 'united states')

0        united states
1        united states
2        united states
3        united states
4        united states
             ...
34862           france
34863           france
34864           france
34865           france
34866              NaN
Name: Country, Length: 34867, dtype: object

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34867 entries, 0 to 34866
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             34867 non-null  float64
 1   Date              34866 non-null  datetime64[ns]
 2   Year              34867 non-null  float64
 3   Month             34866 non-null  object
 4   Customer Age      34867 non-null  Int64
 5   Customer Gender   34866 non-null  object
 6   Country           34866 non-null  object
 7   State             34866 non-null  object
 8   Product Category  34866 non-null  object
 9   Sub Category      34866 non-null  object
 10  Quantity          34867 non-null  float64
 11  Unit Cost         34867 non-null  float64
 12  Unit Price        34867 non-null  float64
 13  Cost              34867 non-null  float64
 14  Revenue           34867 non-null  float64
 15  Column1           34867 non-null  float64
 16  Status            34867 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(8), object(7)
memory usage: 4.6+ MB

In [70]:
df.head()

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Column1,Status
0,0.0,2016-02-19,2016.0,February,29,F,united states,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.0,0.0,Low
1,1.0,2016-02-20,2016.0,February,29,F,united states,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.0,0.0,Low
2,2.0,2016-02-27,2016.0,February,29,F,united states,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.0,0.0,Low
3,3.0,2016-03-12,2016.0,March,29,F,united states,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.0,0.0,Low
4,4.0,2016-03-12,2016.0,March,29,F,united states,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.0,0.0,Low